project_id = "iurpztuixojhjbkwqkrw"

[functions.chat]
verify_jwt = false

[functions.github]
verify_jwt = false

[functions.admin-bootstrap]
verify_jwt = false

[functions.custom-db-setup]
verify_jwt = false
